### ISSUE TITLE
Windows usage instructions

### ISSUE THREAD

**Issue by markgibbons25** [twardoch/svgop#3]
Hi I've tried to run svgop.exe 0.8 and its not doing anything.
`.\svgop.exe --input=".\small.svg" --output=".\smallout.svg"`

No errors no output nothing.

**Comment by twardoch** [comment]
Same as with macOS, use pipes (redirection). 

`svgop.exe < input.svg > output.svg`

should work. Does it?

**Comment by markgibbons25** [comment]
Ah thanks, it works in command prompt but not powershell.

**Comment by twardoch** [comment]
They say 

```
Get-Content test.svg | ./svgop.exe > test.min.svg
```

would be the equivalent in PowerShell. Can you check?
