### ISSUE TITLE
Keeping the binary small

### ISSUE THREAD

**Issue by mdeweerd** [twardoch/svgop#8]
I noticed that you like to keep the binary small - excellent.

Two tips:
- use "strip" on the generated executeable or add the compile option to not include debug information;
- Use an executeable compression tool - fupx or other one.

The resulting exe file is "only" 20448256 bytes - smaller than the zip ;-).

Note: unfortenately the packed version did not work... I did not investigate further.

**Comment by twardoch** [comment]
Well, I myself built it on a Mac, not sure how to do it but feel free to contribute a PR

**Comment by mdeweerd** [comment]
Ok, I was mainly making a suggestion, if you're building on mac, its a bit more complex to optimize for windosws
